### ISSUE TITLE
distanceTo

### ISSUE THREAD

**Issue by coderguy42** [stevekrouse/WoofJS#70] opened 2016-05-21 21:18 UTC
At some seemingly random point after running my code, the circle disappears, and the console fills with alternating lines of text "Script error. (line 0)" and "error". The line 0 thing could mean that the problem is not in the javascript, but the woof libraries. In the console, the "error" message is first.

This is my code:

                 // Set up your Woof project
var project = new Woof.Project({fullScreen: true, debug: ["project.sprites"]}); 
project.setBackdropURL("http://efdreams.com/data_images/dreams/sky/sky-05.jpg");
var circle = project.addCircle({radius: 10, color: "black"});
project.every(40, "milliseconds", () => {
  circle.radius = circle.distanceTo(project.mouseX, project.mouseY);
});

**Comment by stevekrouse** [comment] 2016-05-22 17:16
I am not able to reproduce this error, so I think it's a JBin issue... Closing for now...

**Closed by stevekrouse** 2016-05-22 17:16 UTC
